var sentences = [
[
	"Bonjour mes chers étudiants!",
	"Alors, vous avez bien travaillé votre TD et lu la page 88 de mon poly?",
	"Bien! Alors, ouvrez votre poly page 45 sur le cas Lenoir.",
	"J'espère que vous avez eu le temps de lire le cas Saari.",
	"Maintenant qu'on a terminé la marée fraternelle...",
	"On va pouvoir commencer les flux d'exploitations.",
	"Ouvrez votre poly Chapitre II ter page 23(b).",
	"Sur le cas Lenoir, et completez donc le bilan des comptes.",
	"Faites ensuite le bilan prévisionnel pour l'exercice N+2 bhh.",
	"Vous avez le plan comptable dans votre poly!",
],
[
	"Est-ce que vous avez terminé votre PPP??",
	"Moi je comprends pas! Vous êtes des spécialistes du traitement de l'information!",
	"Bah! C'est quand même pas compliqué! Moi je sais pas!",
	"Est-ce que vous avez lu votre poly page 87(b)! Bah!",
	"Moi je comprends pas! Vous avez les ressources..",
	"Et le bilan prévisionnel m'enfin?",
	"C'est la classe 6 pour les taxes!! C'est le compte 63512, mais ouvrez votre poly bon sang!",
	"Si vous prenez pas en compte les immobilisations et les amortissements...",
	"On a pourtant vu ça en amphi! hh-h-h, je comprends pas moi!",
	"Vous avez des emprunts à rembourser, des créances!",
	"Est-ce que vous avez consulté les documents comptables?",
	"C'est pour ça qu'on les fait!",
	"Si vous avez assez de fonds propres, vous avez des solutions!",
	"Rappelez-vous enfin! Dans la marée fraternelle! Bhh",
	"Les créances et les dettes fournisseurs!",
	"Vous savez bien! Vous êtes des informaticiens, des spécialites! Hhh",
	"Comment voulez-vous envisager sereinement la suite du programme!",
	"Vous ne savez même pas faire un bilan des comptes!!"
],
[
	"M. BOCHÉ! AU TABLEAU!",
	"B'ENFIIN MAIS! JE COMPRENDS PAS!",
	"VOUS ÊTES INFORMATICIEN!",
	"VOUS ÊTES DES SPÉCIALISTES DU TRAITEMENT DE L'INFORMATION!!!",
	"BHH-H-H",
	"ET VOTRE PÉPÉPÉ!?! EST-CE QUE VOUS AVEZ CRÉE VOTRE RÉSEAU PROFESSIONNEL?!",
	"ET LE POZTÈRE!! BHHH!!",
	"EST-CE QUE VOUS AVEZ FAIT DES SLAÏCES?!",
	"H-H-H-H",
	"MAIS C'EST LE COMPTE 512 B'ENFIN!",
	"ET LA TAXEEE!!",
	"MAIS L'EBE!! SANS LE BFR BH-H-H! COMMENT VOULEZ-VOUS QUE ÇA MARCHE!!!",
	"MOI JE COMPRENDS PAS!!!",
	"MAAIIIS EST-CEE QUE VOUS CONNAISSEZ VOTRE CODE POSTAL AU MOINSSS!!",
	"BAHAAAAAAAHHHHHHHHHHH",
	"BON SANG MAIS! H-H",
	"ON AVEZ POURTANT DÉJÀ VU ÇA DANS LE CAS TOUMODE, LE CAS LENOIR, LE CAS SAARI!! BH!",
	"VOUS VOUS RENDEZ PAS COMPTE DE LA CHANCE QUE VOUS AVEZ!",
]];